Controllers/PostsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shortcutt.Data;
using Shortcutt.Models;
using Shortcutt.ViewModels;
using System.Diagnostics;
using System.Security.Claims;

namespace Shortcutt.Controllers
{
    public class PostsController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IWebHostEnvironment _env;
        private readonly ApplicationDbContext _context;

        public PostsController(ILogger<HomeController> logger, ApplicationDbContext context, IWebHostEnvironment env)
        {
            _logger = logger;
            _context = context;
            _env = env;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreatePost inputs)
        {
            if (ModelState.IsValid)
            {
                var post = inputs.MapToPost();
                post.UserId =  User.FindFirstValue(ClaimTypes.NameIdentifier);
                await _context.Posts.AddAsync(post);
                if (inputs.Image is not null)
                {
                    var filePath = Path.Combine(_env.WebRootPath,"images",
                        Path.GetRandomFileName() + Path.GetExtension(inputs.Image.FileName));

                    using (var stream = System.IO.File.Create(filePath))
                    {
                        await inputs.Image.CopyToAsync(stream);
                    }
                }
                ViewData["message"] = "پست با موفقیت ثبت شد.";
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ag</title>
    <link rel="icon" type="image/x-icon" href="~/images/icon.png">
    <link rel="stylesheet" href="~/lib/bootstrap5/css/bootstrap.rtl.min.css" />
    <link href="https://cdn.jsdelivr.net/gh/rastikerdar/vazir-font@v30.1.0/dist/font-face.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ShortCutt.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" style="font-size:18px">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/icon.png" height="64" width="64" alt="site icon" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item d-inline-flex">
                            <i class="gg-home my-auto"></i><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">خانه</a>
                        </li>
                        <li class="nav-item d-inline-flex">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Posts" asp-action="Create">ارسال آگهی</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ShortCutt - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap5/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>